"use client";

import { motion } from "framer-motion";
import { Fingerprint, Hash, FileCode, Braces } from "lucide-react";
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import type { VerificationResult } from "./VerificationResultCard";

interface ForensicAccordionProps {
  result: VerificationResult;
}

export function ForensicAccordion({ result }: ForensicAccordionProps) {
  const forensicSections = [
    {
      id: "fingerprint",
      icon: Fingerprint,
      title: "Fingerprint Statistics",
      content: (
        <div className="space-y-3">
          {result.details.map((d) => (
            <div
              key={d.label}
              className="flex items-center justify-between rounded-lg bg-secondary/50 px-3.5 py-2.5"
            >
              <span className="text-[13px] text-muted-foreground">{d.label}</span>
              <span className="text-[13px] font-semibold">{d.value}%</span>
            </div>
          ))}
        </div>
      ),
    },
    {
      id: "model",
      icon: Braces,
      title: "Model Identification",
      content: (
        <div className="space-y-2.5">
          {[
            { label: "Model Name", value: result.modelOrigin },
            { label: "Version", value: "v2.1.0" },
            { label: "Provider", value: "OpenAI" },
            { label: "Detection Method", value: "Token Distribution Analysis" },
          ].map((item) => (
            <div
              key={item.label}
              className="flex items-center justify-between rounded-lg bg-secondary/50 px-3.5 py-2.5"
            >
              <span className="text-[13px] text-muted-foreground">{item.label}</span>
              <span className="text-[13px] font-semibold">{item.value}</span>
            </div>
          ))}
        </div>
      ),
    },
    {
      id: "hash",
      icon: Hash,
      title: "Cryptographic Hash",
      content: (
        <div className="space-y-2.5">
          <div className="rounded-lg bg-secondary/50 px-3.5 py-2.5">
            <p className="mb-1 text-[11px] font-medium text-muted-foreground">SHA-256</p>
            <p className="break-all font-mono text-[12px]">{result.hash}</p>
          </div>
          <div className="rounded-lg bg-secondary/50 px-3.5 py-2.5">
            <p className="mb-1 text-[11px] font-medium text-muted-foreground">Verification Timestamp</p>
            <p className="font-mono text-[12px]">{result.timestamp}</p>
          </div>
        </div>
      ),
    },
    {
      id: "summary",
      icon: FileCode,
      title: "Summary",
      content: (
        <div className="rounded-lg bg-secondary/50 px-3.5 py-3">
          <p className="text-[13px] leading-relaxed text-muted-foreground">
            {result.found
              ? `A cryptographic watermark was detected with ${result.confidence}% confidence. The content appears to have been generated by ${result.modelOrigin}. The embedded fingerprint matches known watermarking patterns and can be used for forensic attribution.`
              : `No detectable watermark was found in the submitted content. This may indicate the content was not generated by a watermarked model, or the watermark has been removed or degraded below the detection threshold.`}
          </p>
        </div>
      ),
    },
  ];

  return (
    <motion.div
      initial={{ opacity: 0, y: 12 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.3, delay: 0.2 }}
    >
      <Card className="border-border/40 shadow-sm" id="forensics">
        <CardHeader className="pb-3">
          <CardTitle className="text-[15px]">Forensic Details</CardTitle>
        </CardHeader>
        <CardContent>
          <Accordion type="single" collapsible className="w-full">
            {forensicSections.map((section) => {
              const Icon = section.icon;
              return (
                <AccordionItem
                  key={section.id}
                  value={section.id}
                  className="border-border/40"
                >
                  <AccordionTrigger className="py-3 text-[13px] font-medium hover:no-underline">
                    <div className="flex items-center gap-2.5">
                      <div className="flex size-7 items-center justify-center rounded-lg bg-secondary">
                        <Icon className="size-3.5 text-muted-foreground" />
                      </div>
                      {section.title}
                    </div>
                  </AccordionTrigger>
                  <AccordionContent className="pb-4 pt-1">
                    {section.content}
                  </AccordionContent>
                </AccordionItem>
              );
            })}
          </Accordion>
        </CardContent>
      </Card>
    </motion.div>
  );
}
